vich_uploader:
    db_driver: orm
    twig: true            # set to false to disable twig integration
    form: true            # set to false to disable form integration
    storage: file_system  # or gaufrette or flysystem
    metadata:
        auto_detection: true
        cache: file
        type: annotation  
    mappings:
       carousel:
            uri_prefix: '%kernel.project_dir%/public/images/carousel'
            upload_destination: '%kernel.project_dir%//public/images/carousel'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
